function B = B_3r(param,m1,m2,m3,q)
%B_3r
%    B = B_3r(A2,A3,AL2,AL3,D2,D3,M1,M2,M3,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Jun-2022 02:39:08

d1  = param(1);
al2 = param(2);
d2  = param(3);
al3 = param(4);
d3  = param(5);
a2  = param(6);
a3  = param(7);

q1 = q(1);
q2 = q(2);
q3 = q(3);

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = a3+al3;
t6 = d2+d3;
t7 = m2+m3;
t8 = q2+q3;
t9 = a2.^2;
t10 = a3.^2;
t11 = al2.^2;
t12 = al3.^2;
t13 = d2.^2;
t14 = q2.*2.0;
t15 = q3.*2.0;
t16 = a2.*al2.*2.0;
t17 = a3.*al3.*2.0;
t19 = a2.*d2.*m2;
t20 = al2.*d3.*m3;
t18 = cos(t14);
t21 = sin(t8);
t22 = t13.*2.0;
t23 = q2+t8;
t25 = al2.*d2.*t7;
t26 = t8.*2.0;
t27 = al2.*t3.*t5;
t24 = cos(t23);
t28 = cos(t26);
t29 = m3.*t5.*t6.*t21;
t30 = t19+t20+t25;
t33 = t10+t12+t17+t27+1.105820133333333e-1;
t31 = t4.*t30;
t34 = m3.*t33;
t32 = t29+t31;
mt1 = [m1.*2.8125e-3+(m2.*(t9+t11+t16+t22+t18.*(a2+al2).^2))./2.0+m3.*(t2.*t3-t4.*sin(q3)).^2.*1.105820133333333e-1+m2.*t2.^2.*1.2625425e-1+m2.*t4.^2.*2.8125e-3+m3.*t21.^2.*2.8125e-3+(m3.*(t10+t11+t12+t17+t22+t27.*2.0+d2.*d3.*4.0+t11.*t18+t10.*t28+t12.*t28+t17.*t28+d3.^2.*2.0+a3.*al2.*t24.*2.0+al2.*al3.*t24.*2.0))./2.0,t32,t29,t32];
mt2 = [m3.*t27.*2.0+m3.*(t10+t11+t12+t17+1.105820133333333e-1)+m2.*(t9+t11+t16+1.2625425e-1),t34,t29,t34,m3.*(t10+t12+t17+1.105820133333333e-1)];
B = reshape([mt1,mt2],3,3);
