function FK = FK_3r(param,q)
%FK_3r
%    FK = FK_3r(AL2,AL3,D1,D2,D3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Jun-2022 22:55:34

d1  = param(1);
al2 = param(2);
d2  = param(3);
al3 = param(4);
d3  = param(5);
a2  = param(6);
a3  = param(7);

q1 = q(1);
q2 = q(2);
q3 = q(3);

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = d2+d3;
t6 = q2+q3;
t7 = al2.*t3;
t8 = cos(t6);
t9 = sin(t6);
t10 = al3.*t8;
t11 = t7+t10;
FK = reshape([t2.*t8,t4.*t8,-t9,0.0,-t2.*t9,-t4.*t9,-t8,0.0,-t4,t2,0.0,0.0,-t4.*t5+t2.*t11,t2.*t5+t4.*t11,d1-al3.*t9-al2.*sin(q2),1.0],[4,4]);
