function Y_t = Y_fun(g,param,ddq,dq,q)
%Y_fun
%    Y_t = Y_fun(A2,A3,AL2,AL3,D2,D3,DDQ1,DDQ2,DDQ3,DQ1,DQ2,DQ3,G,M2,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Jun-2022 15:58:20

m2=0;

d1  = param(1);
al2 = param(2);
d2  = param(3);
al3 = param(4);
d3  = param(5);
a2  = param(6);
a3  = param(7);

q1 = q(1);
q2 = q(2);
q3 = q(3);

dq1 = dq(1);
dq2 = dq(2);
dq3 = dq(3);

ddq1 = ddq(1);
ddq2 = ddq(2);
ddq3 = ddq(3);


t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = a2+al2;
t7 = a3+al3;
t8 = d2+d3;
t9 = q2+q3;
t10 = a2.^2;
t11 = a3.^2;
t12 = al2.^2;
t13 = al3.^2;
t14 = d2.^2;
t15 = dq1.^2;
t16 = dq2.^2;
t17 = dq3.^2;
t18 = m2+1.0;
t19 = q2.*2.0;
t20 = q3.*2.0;
t21 = a2.*al2.*2.0;
t22 = a3.*al3.*2.0;
t23 = a3.*al3.*4.0;
t43 = ddq1.*2.8125e-3;
t24 = t2.^2;
t25 = sin(t19);
t26 = cos(t9);
t27 = sin(t9);
t28 = t11.*2.0;
t29 = t13.*2.0;
t30 = ddq1.*t14;
t31 = q2+t9;
t34 = al2.*d2.*ddq2.*t4;
t35 = t9.*2.0;
t36 = al2.*t3.*t7;
t37 = g.*t2.*t6;
t38 = d2.*ddq1.*t4.*t6;
t41 = al2.*d2.*t2.*t16;
t46 = t10+t12+t21+1.2625425e-1;
t47 = t10+t12+t21+1.2344175e-1;
t32 = cos(t31);
t33 = sin(t31);
t39 = cos(t35);
t40 = sin(t35);
t42 = -t37;
t44 = dq1.*dq2.*t12.*t25;
t48 = ddq2.*t46;
t49 = t23+t28+t29+2.155390266666667e-1;
t50 = t11+t13+t22+t36+1.105820133333333e-1;
t45 = -t44;
t51 = t40.*t49;
et1 = ddq1.*5.669725666666667e-2+t30+t34+t41+t45+(ddq1.*t11)./2.0+(ddq1.*t12)./2.0+(ddq1.*t13)./2.0+ddq1.*t39.*5.388475666666667e-2+d3.^2.*ddq1+(ddq1.*t12.*cos(t19))./2.0+a3.*al3.*ddq1+d2.*d3.*ddq1.*2.0-dq1.*dq2.*t40.*1.077695133333333e-1;
et2 = dq1.*dq3.*t40.*(-1.077695133333333e-1)+(ddq1.*t11.*t39)./2.0+(ddq1.*t13.*t39)./2.0+a3.*d2.*t16.*t26+a3.*d2.*t17.*t26+a3.*d3.*t16.*t26+a3.*d3.*t17.*t26+al2.*d3.*t2.*t16+al3.*d2.*t16.*t26+al3.*d2.*t17.*t26+al3.*d3.*t16.*t26+al3.*d3.*t17.*t26-dq1.*dq2.*t11.*t40-dq1.*dq3.*t11.*t40-dq1.*dq2.*t13.*t40-dq1.*dq3.*t13.*t40+a3.*al2.*ddq1.*t3+a3.*al2.*ddq1.*t32+a3.*al3.*ddq1.*t39+al2.*al3.*ddq1.*t3+al2.*al3.*ddq1.*t32+a3.*d2.*ddq2.*t27+a3.*d2.*ddq3.*t27+a3.*d3.*ddq2.*t27+a3.*d3.*ddq3.*t27+al2.*d3.*ddq2.*t4+al3.*d2.*ddq2.*t27+al3.*d2.*ddq3.*t27+al3.*d3.*ddq2.*t27+al3.*d3.*ddq3.*t27;
et3 = -a3.*al2.*dq1.*dq3.*t5-a3.*al2.*dq1.*dq2.*t33.*2.0-a3.*al2.*dq1.*dq3.*t33-a3.*al3.*dq1.*dq2.*t40.*2.0-a3.*al3.*dq1.*dq3.*t40.*2.0-al2.*al3.*dq1.*dq3.*t5-al2.*al3.*dq1.*dq2.*t33.*2.0-al2.*al3.*dq1.*dq3.*t33+a3.*d2.*dq2.*dq3.*t26.*2.0+a3.*d3.*dq2.*dq3.*t26.*2.0+al3.*d2.*dq2.*dq3.*t26.*2.0+al3.*d3.*dq2.*dq3.*t26.*2.0;
mt1 = [t43,0.0,0.0,t30+t34+t41+t43+t45+ddq1.*t24.*1.2344175e-1-dq1.*dq2.*t25.*1.2344175e-1+ddq1.*t10.*t24+ddq1.*t12.*t24+ddq1.*t21.*t24+a2.*d2.*t2.*t16-dq1.*dq2.*t10.*t25+a2.*d2.*ddq2.*t4-a2.*al2.*dq1.*dq2.*t25.*2.0,t38+t42+t48+t2.*t4.*t15.*t47,0.0,et1+et2+et3];
mt2 = [-g.*(t7.*t26+t2.*(a2.*m2+al2.*t18))+ddq3.*t50-m2.*(t38+t42+t48+(t15.*t25.*t47)./2.0)+ddq1.*(t4.*(al2.*d3+a2.*d2.*m2+al2.*d2.*t18)+t7.*t8.*t27)+(t15.*(t51+t25.*(t12.*2.0+m2.*t47.*2.0)+al2.*t7.*t33.*4.0))./4.0+ddq2.*(t12+t36+t50+m2.*t46)-al2.*dq3.*t5.*t7.*(dq2+dq3)-al2.*dq2.*dq3.*t5.*t7,ddq3.*(t11+t13+t22+1.105820133333333e-1)+ddq2.*t50+(t15.*(t51+al2.*t5.*t7.*2.0+al2.*t7.*t33.*2.0))./4.0-g.*t7.*t26+al2.*t5.*t7.*t16+ddq1.*t7.*t8.*t27];
Y_t = reshape([mt1,mt2],3,3);
